vendor: Teamsun
name:  TCMS
version: 6.2
website_url: http://www.teamsun.com.cn/
documentation_url: http://www.teamsun.com.cn/
product_logo_url: https://landscape.cncf.io/logos/teamsun-member.svg
type: distribution
description: Teamsun Technology offers IT applications and services for the development of computer information systems.
