vendor: acornsoft
name: Cocktail Cloud
version: v4.6.6
website_url: https://www.cocktailcloud.io/cocktail/cloud.do
documentation_url: https://cocktailcloud.gitbook.io/cocktail-cloud-en
product_logo_url: http://cocktailcloud.io/wp-content/uploads/2019/03/cocktailcloud_acornsoft.svg
type: distribution
description: 'A cocktail cloud is a container application management platform that provides a continuous development/deployment/operating environment for container-based applications.'
