vendor: UCloud
name: UCloud Kubernetes Service（UK8S）
version: v1.20.6
website_url: https://www.ucloud.cn/site/product/uk8s.html
documentation_url: https://docs.ucloud.cn/uk8s/
product_logo_url: https://www.cncf.io/wp-content/uploads/2019/03/ucloud.svg
type: hosted & dedicated
description: 'UK8S is a container service base on Kubernetes,integrated with  cloud product of UCloud platform.'
