vendor: acornsoft
name: Cocktail
version: v3.1
website_url: http://www.cocktailcloud.io/what-is-cocktail-cloud/
documentation_url: https://acornapps.github.io/cocktail-manual-3.1.1/docs/en/0.0/
product_logo_url: 
type: 
description: '************'
