vendor: Alauda
name: Alauda Kubernetes (AKS)
version: 1.2
website_url: http://www.alauda.cn/product/detail/id/240.html
documentation_url: http://www.alauda.cn/product/detail/id/240.html
product_logo_url: https://enterprise.alauda.cn/static/images/logo/logo-login-large.svg
type: distribution
description: An Enterprise-Ready Kubernetes Distribution
