vendor: Open Telekom Cloud
name: Open Telekom Cloud Cloud Container Engine
version: v1.19.8-r0-CCE21.1.1.B003-19.38.1
website_url: https://open-telekom-cloud.com/en/products-services/cloud-container-engine
documentation_url: http://docs.otc.t-systems.com/cce/index.html
type: hosted
description: Cloud Container Engine (CCE) provides highly scalable, high-performance, enterprise-class Kubernetes clusters. CCE supports native Kubernetes applications, tools and easy setup of container runtime environment
