vendor: D2iQ
name: DKP
version: v2.4.0-alpha.2
website_url: https://docs.d2iq.com
documentation_url: https://docs.d2iq.com
product_logo_url: https://assets.d2iq.com/production/assets/D2iQ-logo.svg
type: distribution
description: 'DKP is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'
