vendor: D2iQ
name: Konvoy
version: v1.0.0
website_url: https://d2iq.com/solutions/ksphere/konvoy
documentation_url: https://docs.d2iq.com/ksphere/konvoy/
product_logo_url: https://docs.d2iq.com/assets/D2IQ_Logotype_Color_Positive.png
type: distribution
description: 'Konvoy is a standalone distribution of Kubernetes that includes a native Kubernetes cluster pre-packaged for deployment with a complement of best-in-class add-on services enabled by default and ready for immediate use.'
