vendor: Ventus Cloud AG
name: Ventus Cloud Kubernetes Service
version: v1.17.3
website_url: https://ventuscloud.eu/products/kubernetes
documentation_url: https://ventuscloud.eu/docs/kubernetes
type: hosted platform
description: 'Automate container deployment, scaling and management through the Ventus Cloud.'
