vendor: Diamanti Inc
name: Diamanti-Spektra
version: 3.0
website_url: https://diamanti.com
documentation_url: https://support.diamanti.com
product_logo_url: https://diamanti.com/wp-content/uploads/2018/07/Diamanti-Logo-Stacked.jpg
type: distribution
description: 'Diamanti Spektra'
