vendor: Microsoft
name: Azure Kubernetes Service AKS
version: v1.18.8
website_url: https://docs.microsoft.com/en-us/azure/aks/
documentation_url: https://docs.microsoft.com/en-us/azure/aks/
product_logo_url: https://i1.wp.com/buildazure.com/wp-content/uploads/2017/09/Azure.png
type: hosted platform
description: 'AKS allows you to quickly deploy a production ready Kubernetes cluster in Azure.'
