vendor: Qimai
name: MiaoYun
version: v18.12.1
website_url: https://miaoyun.io/
documentation_url: https://miaoyun.io/
# FIXME: LOGO有问题
product_logo_url: miaoyun.io/wp-content/uploads/2019/01/logo@2x.png
type: distribution
