vendor: Alauda
name:  Alauda Container Platform (ACP)
version: 3.12
website_url: http://www.alauda.cn/product/detail/id/364.html
documentation_url: http://www.alauda.cn/product/detail/id/364.html
product_logo_url: https://www.alauda.cn/Public/Home/images/logo.svg
type: distribution
description: A Cloud-Native Application Platform based on Kubernetes
contact_email_address: marketing@alauda.io
