vendor: Docker
name: Docker Desktop for Mac
version: 3.1.0
website_url: https://hub.docker.com/editions/community/docker-ce-desktop-mac
documentation_url: https://docs.docker.com/docker-for-mac/
product_logo_url: https://www.docker.com/sites/default/files/vertical_large.png
type: distribution
description: The fastest and easiest way to get started with Docker on Mac.
