vendor: Hewlett Packard Enterprise (HPE)
name: HPE Ezmeral Runtime Enterprise
version: 5.5
website_url: hpe.com/info/containers
documentation_url:  N/A
product_logo_url: https://github.com/hpe-design/logos/blob/master/HPE%20Primary%20Logo%20-%20SVG/hpe-logo-color.svg
type: Distribution
description: The HPE Ezmeral Runtime Enterprise is a secure, enterprise-grade platform to deploy cloud-native and non-cloud-native applications at scale across your data centers, multiple clouds, and at the edge.