vendor: Cloud 66 Maestro
name: Cloud 66 Maestro
version: v1.207
website_url: https://www.cloud66.com/containers/maestro
documentation_url: https://help.cloud66.com/maestro/
product_logo_url: https://help.cloud66.com/images/ui/maestro_logo.svg
