vendor: Harmonycloud 
name: Harmonycloud Container Platform 
version: v3.3.1 
website_url: https://harmonycloud.cn/ 
documentation_url: https://harmonycloud.cn/product/1 
product_logo_url: https://harmonycloud.cn/uploads/images/202111/57a4c075bbce4984807c0826ac917444.png 
type: distribution 
description: Harmonycloud Container Platform is an Enterprise Platform-as-a-Service based on Kubernetes
contact_email_address: shenzhe@harmonycloud.cn