vendor: Fujitsu  Limited
name: FUJITSU Hybrid IT Service FJcloud-V Kubernetes Service Hatoba
version: v1.20.1
website_url: https://pfs.nifcloud.com/service/hatoba.htm
documentation_url: https://pfs.nifcloud.com/spec/hatoba/
product_logo_url: https://landscape.cncf.io/logos/fujitsu-member.svg
type: hosted
description: 'FJcloud-V Kubernetes Service Hatoba is a managed Kubernetes as a Service to deploy enterprise container applications and operate them simply and useful on FJcloud-V. FJcloud-V is the resale product name of NIFCLOUD.'



