vendor: Aqua Security
name: Aqua Container Security Platform
version: v2.6.3
website_url: https://aquasec.com
documentation_url: https://www.aquasec.com/products/aqua-container-security-platform/
product_logo_url: https://www.aquasec.com/wp-content/uploads/2017/12/aqua_logo_fullcolor.svg