vendor: Kubernative
name: LIMA
version: lima 040 beta
website_url: https://kubernative.net/en/
repo_url: http://www.kubernative.net/images/Downloads/lima-040beta-1el7x86_64.rpm
documentation_url: http://www.kubernative.net/images/Downloads/LIMA/Documentation_LIMA_040_beta.pdf
product_logo_url: http://www.kubernative.net/images/Logos/Kubernative_CNCF.svg
type: distrubution
description: LIMA is a business-tailored kubernetes distribution designed for production environments. Our mission is to provide a new level of security and comfort for vanilla Kubernetes. It covers cluster lifecycle management and infrastructure managemnt optimized for productive enrivonments.
