vendor: Ant Financial
name: Alibaba Cloud Container Service for Kubernetes
version: v1.12.5
website_url: https://tech.antfin.com
documentation_url: https://tech.antfin.com/docs/2/89361
product_logo_url: https://raw.githubusercontent.com/alipay/SOFAStack/master/SOFAStack.svg
type: hosted
description: "SOFAStack CAFE (Cloud Application Fabric Engine), is a PaaS product providing full application life-cycle management, including deployment, orchestration, observability, and disaster recovery for the critical financial business scenarios with classic and cloud native architectural platform support."
