vendor: Intellect Design Arena Inc
name: Intellect FABRIC
version: v18.4.0
website_url: https://www.intellectseec.com/
documentation_url: https://www.intellectseec.com/insurtech-platform
product_logo_url: https://github.com/intellectdesign/intellectseeclogo/blob/master/IntellectSEEC_Logo.svg 
