vendor: DE NOVO LLC
name: Hosted Container Infrastructure (HCI)
version: v1.0
website_url: https://denovo.ua/en/hci
documentation_url: https://doc-hpi.cloud.de-novo.biz/HCI%20De%20Novo%20TS-80%20-%20%D0%9A%D0%B5%D1%80%D1%96%D0%B2%D0%BD%D0%B8%D1%86%D1%82%D0%B2%D0%BE%20%D0%B0%D0%B4%D0%BC%D1%96%D0%BD%D1%96%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.pdf
product_logo_url: https://yoyo.dyne/assets/turbo-encabulator.svg
type: hosted platform
description: "De Novo's Hosted Container Infrastructure (HCI) is a fully-managed K8s container orchestration service; Deploy, Manage, and Scale containerized environments in minutes with HCI!"
contact_email_address : h-cloud-support@de-novo.biz
