vendor: Mantech
name: Accordion
version: v2.4.0
website_url: https://accordions.co.kr/kube_eng/
documentation_url: https://demo.accordions.co.kr/docs/
product_logo_url: https://drive.google.com/file/d/13W74c6fC67P9Ahsl_mHHSLbFLl-KQ6zS/view?usp=share_link
type: distribution
description: 'Accordion Kubernetes Platform help you to orchestrate containerized workloads for your DevOps practices & CI/CD pipelines, delivering enhanced developer productivity and accelerating time to market.'
