vendor: iNNOVO Cloud GmbH
name: iNNOVO Managed Kubernetes Engine
version: v1.15.0
website_url: https://www.innovo-cloud.de/produktgruppen/kubernetes-as-a-service-de/
documentation_url: https://docs.imke.cloud
product_logo_url: https://docs.imke.cloud/user/themes/learn2/images/logo.eps
type: hosted platform
description: 'iMKE - iNNOVO Managed Kubernetes Engine. The first choice for Industrial and Finance clients Kubernetes.'
