vendor: Microsoft
name: Azure Stack
version: v0.36.2
website_url: https://azure.microsoft.com/en-us/overview/azure-stack/
documentation_url: https://aka.ms/aksenginedoc
product_logo_url: https://i1.wp.com/buildazure.com/wp-content/uploads/2017/09/Azure.png