vendor: Spectro Cloud
name: Palette
version: v2.1.9
website_url: https://spectrocloud.com
documentation_url: https://docs.spectrocloud.com
product_logo_url: https://www.spectrocloud.com/static/9ba77b98004650ec30c5f50f0f0ba906/3e2e0/palette-logo-white.png
type: distribution
description: Keep control of your Kubernetes infrastructure stack with Spectro Cloud’s as-a-Service experience for public clouds, private clouds, and bare metal environments
