vendor: NeuVector Inc. 
name: NeuVector Container Services
version: 1.3.1.1748
website_url: https://neuvector.com/
documentation_url: https://neuvector.com/products
product_logo_url: https://neuvector.com/wp-content/uploads/2016/09/LogoRW-Med-1.png
