vendor: Open Telekom Cloud - OTC
name: Open Telekom Cloud - Cloud Container Engine - CCE
version: v1.25.2-r0-CCE22.12.1
website_url: https://open-telekom-cloud.com/en/products-services/cloud-container-engine
documentation_url: http://docs.otc.t-systems.com/cce/index.html
type: hosted
description: Cloud Container Engine (CCE) provides highly scalable, high-performance, enterprise-class Kubernetes clusters. CCE supports native Kubernetes applications, tools and easy setup of container runtime environment
contact_email_address: oliver.eotvos@t-systems.com
