vendor: DaoCloud
name: DaoCloud Enterprise
version: v5.0.0
website_url: https://docs.daocloud.io/
documentation_url: https://docs.daocloud.io/dce/what-is-dce/
product_logo_url: https://guide.daocloud.io/download/attachments/524290/global.logo?version=2&modificationDate=1469173304363&api=v2
type: distribution
description: 'Daocloud helps you provide a reliable and consistent basic support environment to meet the high SLA requirements of enterprise critical applications
.'
