vendor: ASUS Cloud
name: ASUS CloudInfra 
version: 0.1.0
website_url: www.asuscloud.com
documentation_url: https://drive.google.com/open?id=1C6CjD19dDVtRHT8SzZKx24TK-KtMg9VF
product_logo_url: https://drive.google.com/open?id=1qPKjUjRcvfyBnm0MHZyaS88urE-RhHLR
type: distribution
description: 'helps you bootstrap a Kubernetes cluster'
