vendor: ASUS Cloud
name: ASUS CloudInfra 
version: 0.1.0
website_url: www.asuscloud.com
documentation_url: https://www.asuswebstorage.com/navigate/a/#/s/1CB3AB7F5FA548F1A98B2FD69DD48A91Y 
product_logo_url: https://www.asuswebstorage.com/navigate/a/#/s/8D0FBE9E905249F68E031A5D165FCB6BY
type: distribution
description: 'helps you bootstrap a Kubernetes cluster'