vendor: Samsung SDS
name: SCP Kubernetes Engine (SKE)
version: v1.22.5
website_url: https://cloud.samsungsds.com/serviceportal/product/container/k8sEngine.html
product_logo_url: https://github.com/thdrnsdk/SamsungSDS-Kubernetes-Service/blob/master/logo.jpg
type: hosted
description: SKE allows you to quickly deploy a production ready Kubernetes cluster in Samsung Cloud Platform (SCP).
