on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  verify-conformance:
    runs-on: ubuntu-latest
    steps:
      - name: write-config
        env:
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_HMAC: ${{ secrets.GH_APP_HMAC }}
        run: |
          mkdir -p ./tmp/
          echo '${{ env.GH_APP_PRIVATE_KEY }}' | base64 -d > ./tmp/github-app-private-key
          echo '${{ env.GH_APP_HMAC }}' > ./tmp/hmac
      - name: verify-conformance
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          REPO: ${{ github.repository }}
        run: |
          set -x
          docker run --rm \
            -v "$PWD:$PWD:ro" \
            --workdir "$PWD" \
            ghcr.io/cncf-infra/verify-conformance@sha256:183ed502367f0e0442798935247888077478192120efc753a9d53adf646d97ad \
              --github-endpoint=https://api.github.com \
              --dry-run=false \
              --github-app-id="${{ env.GH_APP_ID }}" \
              --github-app-private-key-path="$PWD/tmp/github-app-private-key" \
              --hmac-secret-file=$PWD/tmp/hmac \
              --repo="$REPO"
      - name: cleanup
        if: ${{ always() }}
        run: |
          rm -rf ./tmp/
